<div class="privacy-container" style="
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: #ffffff;
    padding: 24px 28px;
    border-radius: 8px;
    color: #2d2d2d;
    font-size: 15px;
    line-height: 1.7;
">

  <h2 style="text-align: center; font-size: 24px; color: #1a202c; margin-bottom: 20px;">
    Data Privacy Notice
  </h2>

  <p>
    In compliance with <strong><a href="https://privacy.gov.ph/data-privacy-act/" target="_blank">Republic Act No. 10173</a></strong>,
    also known as the <strong>Data Privacy Act of 2012</strong>, this system recognizes its responsibility to respect
    and protect the personal data of all authorized users, personnel, applicants, and stakeholders.
  </p>

  <p>
    We are committed to ensuring the security and confidentiality of personal information collected, stored,
    accessed, generated, and processed through this platform.
  </p>

  <h4 style="color: #00695c; margin-top: 25px; font-size: 18px;">Purpose of Data Collection</h4>

  <p>The information collected through this system may be used for the following legitimate purposes:</p>
  <ul style="margin-left: 20px; margin-top: 10px;">
    <li>Creating, updating, and maintaining official user, personnel, employment, payroll, leave, attendance, recruitment, and related administrative records</li>
    <li>Processing requests, transactions, applications, reports, approvals, and system-generated documents</li>
    <li>Verifying identity, access rights, roles, and account activity within the system</li>
    <li>Supporting audit, compliance, monitoring, reporting, internal assessment, and record-management requirements</li>
    <li>Improving system security, service delivery, and administrative workflows</li>
  </ul>

  <p>
    Personal data may include information you provide directly, information generated by your use of the system,
    and supporting documents or identifiers required for official transactions. These records will be securely
    maintained by authorized offices and system administrators in accordance with applicable data retention
    policies, security standards, and legal requirements.
  </p>

  <h4 style="color: #00695c; margin-top: 25px; font-size: 18px;">Consent and Acknowledgment</h4>

  <p>
    By using this system, submitting information, or clicking accept, you acknowledge that you have read and
    understood this notice. You voluntarily consent to the collection, recording, organization, updating, use,
    consolidation, storage, retrieval, and processing of your personal data for the purposes stated above.
  </p>

  <p>
    Your data shall be retained only for as long as necessary to fulfill these purposes or as required by law,
    and shall be protected against unauthorized access, disclosure, alteration, loss, or misuse.
  </p>

</div>
